create database RetailStore;
USE RetailStore;


create table Website(
	URL varchar(100) primary key,
	Name Varchar(50)
	);
CREATE TABLE Customer (
    Customer_id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50),
    Address VARCHAR(100),
    Phone_no INT NOT NULL,
    Order_ID INT NOT NULL,
    FOREIGN KEY (Order_ID) REFERENCES ORDERS (ORDER_ID)
);


CREATE TABLE PRODUCT(
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(20),
PRODUCT_QUANTITY INT ,
DESCRIPTION VARCHAR(50),
RATING INT,
CATEGORY_ID INT NOT NULL,
DISCOUNT INT
);

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    PRODUCT_IDS INT,
    FOREIGN KEY (PRODUCT_IDS) REFERENCES PRODUCT (PRODUCT_ID),
    CUSTOMER_IDS INT,
    FOREIGN KEY (CUSTOMER_IDS) REFERENCES Customer (Customer_id),
    ORDER_DATE VARCHAR(10),
    VENDOR_ID INT,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (VENDOR_ID),
    ORDER_STATUS VARCHAR(10) NOT NULL
);


CREATE TABLE VENDOR(

	VENDOR_ID INT primary key NOT NULL,
	VENDOR_NAME VARCHAR(20),
	VENDOR_CONTACT INT NOT NULL
);

CREATE TABLE INVENTORY(
	INVENTORY_NO INT PRIMARY KEY NOT NULL,
	VENDOR_IDS INT NOT NULL,
	FOREIGN KEY(VENDOR_IDS) REFERENCES VENDOR(VENDOR_ID),
	PRODUCT_IDS INT NOT NULL,
	FOREIGN KEY(PRODUCT_IDS) REFERENCES PRODUCT(PRODUCT_ID),
	QUANTITY INT
);

CREATE TABLE CATEGORY (
    CATEGORY_NAME VARCHAR(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CATEGORY_DISC INT,
	CONSTRAINT `Category_check` CHECK ((`category_disc` >= 0 AND `category_discount` < 100))

);
CREATE TABLE Del_agent (
    Agent_id INT PRIMARY KEY NOT NULL,
    Agent_Name VARCHAR(50) NOT NULL,
    Vehicle_info VARCHAR(100),
    Phone_no INT NOT NULL,
    Order_ID INT,
    FOREIGN KEY (Order_ID) REFERENCES ORDERS (ORDER_ID),
    PICKUP_ADDRESS VARCHAR(100) NOT NULL,
    DELIVERY_ADDRESS VARCHAR(100) NOT NULL
);
CREATE TABLE Tracking (
    Tracking_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Agent_ID VARCHAR(50),
    Order_ID INT,
    FOREIGN KEY (Order_ID) REFERENCES ORDERS (ORDER_ID),
	FOREIGN KEY (Agent_ID) REFERENCES Del_agent (Agent_ID)
);
CREATE TABLE Admin(
	Admin_UserName INT PRIMARY KEY,
    Password VARCHAR(50)
);
CREATE TABLE WAREHOUSE (
    Manager INT PRIMARY KEY NOT NULL,
    Address VARCHAR(50),
    Pincode INT
);

CREATE TABLE DISCOUNT

select * from ORDERS






