	create database RetailStore;
	USE RetailStore;


	create table Website(
	URL varchar(100) primary key,
	Name Varchar(50)
	);
drop table Customer	 
CREATE TABLE Customer (
    Customer_id INT PRIMARY KEY,
    Name VARCHAR(50),
    Address VARCHAR(100),
    Phone_no INT NOT NULL,
    Order_ID INT,
    FOREIGN KEY (Order_ID) REFERENCES ORDERS (ORDER_ID)
);


	CREATE TABLE PRODUCT(
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(20),
	PRODUCT_QUANTITY INT ,
	DESCRIPTION VARCHAR(50),
	RATING INT,
	CATEGORY_ID INT NOT NULL,
	DISCOUNT INT
	);

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    PRODUCT_IDS INT,
    FOREIGN KEY (PRODUCT_IDS) REFERENCES PRODUCT (PRODUCT_ID),
    CUSTOMER_IDS INT,
    FOREIGN KEY (CUSTOMER_IDS) REFERENCES Customer (Customer_id),
    ORDER_DATE VARCHAR(10),
    VENDOR_ID INT,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR (VENDOR_ID),
    ORDER_STATUS VARCHAR(10)
);


	CREATE TABLE VENDOR(

	VENDOR_ID INT primary key,
	VENDOR_NAME VARCHAR(20),
	VENDOR_CONTACT INT NOT NULL
	);

	CREATE TABLE INVENTORY(
	INVENTORY_NO INT PRIMARY KEY,
	VENDOR_IDS INT,
	FOREIGN KEY(VENDOR_IDS) REFERENCES VENDOR(VENDOR_ID),
	PRODUCT_IDS INT,
	FOREIGN KEY(PRODUCT_IDS) REFERENCES PRODUCT(PRODUCT_ID),
	QUANTITY INT
	);

	CREATE TABLE CATEGORY (
    CATEGORY_NAME VARCHAR(10) PRIMARY KEY,
    CATEGORY_DISC INT
);
CREATE TABLE Del_agent (
    Agent_id INT PRIMARY KEY,
    Agent_Name VARCHAR(50),
    Vehicle_info VARCHAR(100),
    Phone_no INT NOT NULL,
    Order_ID INT,
    FOREIGN KEY (Order_ID) REFERENCES ORDERS (ORDER_ID)
);
CREATE TABLE Tracking (
    Tracking_id INT PRIMARY KEY,
    Agent_ID VARCHAR(50),
    Order_ID INT,
    FOREIGN KEY (Order_ID) REFERENCES ORDERS (ORDER_ID),
	FOREIGN KEY (Agent_ID) REFERENCES Del_agent (Agent_ID)
);
CREATE TABLE Admin(
	Admin_id INT PRIMARY KEY,
    Password VARCHAR(50),
);
CREATE TABLE WAREHOUSE (
    Manager INT PRIMARY KEY,
    Address VARCHAR(50),
    Pincode INT,
);


select * from ORDERS






